#!/bin/bash

# Instalar dependencias
sudo apt install -y install build-essential libpam0g-dev libxcb-xkb-dev xauth xserver-xorg brightnessctl

# Descargar ziglang
wget https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
tar -xvf zig-x86_64-linux-0.15.2.tar.xz > /dev/null

# Descargar ly
wget https://codeberg.org/fairyglade/ly/archive/v1.2.0.zip
unzip v1.2.0.zip
cd ly

# Compilar y activar servicio de systemd
sudo ~/SAM/zig-linux-x86_64-0.15.2/zig build installexe 
sudo systemctl enable ly.service

cd ~/SAM
