#!/bin/bash

# Instalar dependencias
sudo nala install -y build-essential libpam0g-dev libxcb-xkb-dev xauth xserver-xorg brightnessctl

# Descargar ziglang
wget https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
7z x zig-x86_64-linux-0.15.2.tar.xz
7z x zig-x86_64-linux-0.15.2.tar

# Descargar ly
wget https://codeberg.org/fairyglade/ly/archive/v1.2.0.zip
7z x v1.2.0.zip
cd ly

# Compilar y activar servicio de systemd
sudo ~/SAM/zig-x86_64-linux-0.15.2/zig build installexe 
sudo systemctl enable ly.service

cd ~/SAM
