#!/bin/bash

#===== INSTALACIÓN =====#

# Instalar nala
sudo apt install -y nala

# Paquetes de los repositorios oficiales
pkgs_list="res/paquetes"
sudo nala install -y $(grep -vE '^\s*#' "$pkgs_list" | grep -vE '^\s*$' | sed 's/#.*//' | awk '{$1=$1};1' | tr '\n' ' ') || exit 1

# Instalar flatpak y añadir flathub.com
sudo nala install -y flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Crear carpetas para fuentes
mkdir -p ~/.local/share/fonts

# Descargar FiraMono Nerd Font
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraMono.zip
7z x FiraMono.zip -oFiraMono
cp FiraMono/Fira*.otf ~/.local/share/fonts

# Actualizar cache de fuentes
fc-cache -f

# Instalar Ly (display manager)
bash ~/SAM/res/scripts/ly-install

# Descargar yt-dlp de github
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
chmod +x yt-dlp
sudo mv -f yt-dlp /usr/bin/yt-dlp

# Instalar Starship prompt
curl -sS https://starship.rs/install.sh | sh

# Preguntar si quieres instalar auto-cpufreq
read -p "¿Quieres instalar auto-cpufreq? (s/N): " auto_cpufreq
if [ "$auto_cpufreq" = "s" ] || [ "$auto_cpufreq" = "S" ]; then
    bash ~/SAM/res/auto-cpufreq
else
    echo "No se instalará auto-cpufreq."
fi

#===== CONFIGURACIÓN =====#

# Ocultar el manú GRUB
sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub

# Mostrar rueda giratoria
sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/' /etc/default/grub
sudo plymouth-set-default-theme -R spinner

# Actualizar GRUB
sudo update-grub

# Desactivar archivo .sudo_as_admin_successful
echo 'Defaults !admin_flag' | sudo tee /etc/sudoers.d/no_admin_flag
rm ~/.sudo_as_admin_successful

# Montar USB en /media con udisks2
mkdir -p /etc/udev/rules.d
echo 'ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"' | sudo tee /etc/udev/rules.d/99-udisks2.rules

# Historial de bash en XDG
mkdir -p ~/.local/state/bash && touch ~/.local/state/bash/history
source ~/.bashrc && rm ~/.bash_history

# Archivos de nwg-look en XDG
mkdir -p ~/.config/gtk-2.0 && touch ~/.config/gtk-2.0/gtkrc
mkdir -p ~/.local/share/icons

# Configuracion de git en XDG
mkdir -p ~/.config/git && touch ~/.config/git/config && rm ~/.gitconfig

# Crear carpetas del usuario
xdg-user-dirs-update

# Colocar mis dotfiles
git clone https://github.com/mmgmp/dotfiles
cp -r dotfiles/{.bashrc,.profile,.config,.local} ~/

printf "\nCompletado, puedes reiniciar el ordenador con el comando 'systemctl reboot'\n"
