#!/bin/bash

#===== INSTALACIÓN =====#

pkgs-list="recursos/paquetes"
sudo apt install -y $(grep -vE '^\s*#' "$pkgs-list" | grep -vE '^\s*$' | sed 's/#.*//' | awk '{$1=$1};1' | tr '\n' ' ')

# Instalar sway y complementos
sudo apt install -y sway swayidle swaybg swaylock waybar xwayland tofi xdg-desktop-portal-wlr

# Sway autotiling
sudo apt install -y python3-i3ipc
wget https://raw.githubusercontent.com/nwg-piotr/autotiling/master/autotiling/main.py
mv main.py autotiling && chmod +x autotiling
sudo mv autotiling /usr/bin/autotiling

# Instalar herramientas para compilar
sudo apt install -y build-essential make

# Navegador web
sudo apt install -y firefox-esr

# Multimedia
sudo apt install -y mpv brightnessctl swayimg zathura zathura-pdf-poppler gammastep

# Notificaciones
sudo apt install -y mako-notifier libnotify-bin

# Captura de pantalla
sudo apt install -y grim slurp

# Programas adicionales
sudo apt install -y unzip zip unrar-free 7zip curl network-manager newsboat pass pass-otp neovim abook htop bash-completion udisks2 gh nala fonts-firacode fzf calcurse chafa trash-cli jq poppler-utils

# PolicyKit
sudo apt install -y lxpolkit

# Instalar pinentry-gnome3
sudo apt install -y pinentry-gnome3

# Instalar PipeWire y activar audio
sudo apt install -y pipewire wireplumber pavucontrol
systemctl --user --now enable wireplumber.service

# Instalar flatpak y añadir flathub.com
sudo apt install -y flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Crear carpetas para fuentes
mkdir -p ~/.local/share/fonts

# Descargar FiraMono Nerd Font
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraMono.zip
unzip FiraMono.zip -d FiraMono
cp FiraMono/Fira*.otf ~/.local/share/fonts

# Actualizar cache de fuentes
fc-cache -f -v

# Instalar Ly (display manager)
bash ~/SAM/recursos/ly

# Instalar tema del cursor, iconos y GTK
sudo apt install -y breeze-cursor-theme papirus-icon-theme arc-theme

# Descargar versión de lf mas reciente
wget https://github.com/gokcehan/lf/releases/latest/download/lf-linux-amd64.tar.gz
tar -xvf lf-linux-amd64.tar.gz
sudo mv lf /usr/bin/lf

# Descargar yt-dlp de github
wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
chmod +x yt-dlp
sudo mv -f yt-dlp /usr/bin/yt-dlp

# Instalar Starship prompt
curl -sS https://starship.rs/install.sh | sh

# Preguntar si quieres instalar auto-cpufreq
read -p "¿Quieres instalar auto-cpufreq? (s/N): " auto_cpufreq
if [ "$auto_cpufreq" = "s" ] || [ "$auto_cpufreq" = "S" ]; then
    bash ~/SAM/recursos/auto-cpufreq
else
    echo "No se instalará auto-cpufreq."
fi

# Preguntar si quieres instalar plymouth
read -p "¿Quieres instalar plymouth? (s/N): " plymouth
if [ "$plymouth" = "s" ] || [ "$plymouth" = "S" ]; then
	sudo apt install -y plymouth plymouth-themes
	sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/' /etc/default/grub
	sudo update-grub2
	sudo plymouth-set-default-theme -R spinner
else
	echo "No se instalará plymouth."
fi

#===== CONFIGURACIÓN =====#

# Configurar tiempo de GRUB
read -p "¿Quieres mostrar el menú GRUB? (S/n): " menu_grub
if [ "$menu_grub" = "n" ] || [ "$menu_grub" = "N" ]; then
	sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
else
	echo "Se mostrara el menú GRUB."
fi

# Configurar apariencia de GRUB
git clone https://github.com/vinceliuice/grub2-themes
cd grub2-themes
sudo ./install.sh -b -t vimix -i white
cd ..

# Colocar mis dotfiles
git clone https://github.com/mmgmp/dotfiles
cp -r dotfiles/{.bashrc,.profile,.config,.local} ~/

# Historial de bash en XDG
mkdir -p ~/.local/state/bash && touch ~/.local/state/bash/history
source ~/.bashrc && rm ~/.bash_history

# Archivos de nwg-look en XDG
mkdir -p ~/.config/gtk-2.0 && touch ~/.config/gtk-2.0/gtkrc
mkdir -p ~/.local/share/icons

# Configuracion de git en XDG
mkdir -p ~/.config/git && touch ~/.config/git/config && rm ~/.gitconfig

# Montar USB en /media
mkdir -p /etc/udev/rules.d
echo 'ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"' | sudo tee /etc/udev/rules.d/99-udisks2.rules

# Desactivar archivo .sudo_as_admin_successful
echo 'Defaults !admin_flag' | sudo tee /etc/sudoers.d/no_admin_flag
rm ~/.sudo_as_admin_successful

# Crear carpetas del usuario
xdg-user-dirs-update

# Limpiar restos
cd ..
sudo rm -r --interactive=never SAM/
sudo rm -r --interactive=never go/

printf "\nCompletado, puedes reiniciar el ordenador con el comando 'systemctl reboot'\n"
