#!/bin/bash

# Instalar dependencias
sudo apt install -y libpam0g-dev libxcb-xkb-dev

# Descargar zig 0.12.0
wget https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
tar -xvf zig-linux-x86_64-0.12.0.tar.xz > /dev/null

# Descargar ly
wget https://github.com/fairyglade/ly/archive/refs/tags/v1.0.2.zip
unzip v1.0.2.zip
cd ly-v1.0.2

# Compilar y activar servicio de systemd
sudo ~/SAM/zig-linux-x86_64-0.12.0/zig build installsystemd 
sudo systemctl enable ly.service

cd ~/SAM
