#!/bin/bash

# Instalar dependencias
sudo apt install -y build-essential libpam0g-dev libxcb-xkb-dev

# Descargar zig 0.12.0
wget https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
tar -xvf zig-linux-x86_64-0.12.0.tar.xz > /dev/null

# Descargar ly 1.0.0
wget https://github.com/fairyglade/ly/archive/refs/tags/v1.0.0.zip
unzip v1.0.0.zip > /dev/null
cd ly-1.0.0

# Compilar y activar servicio de systemd
export PATH=$PATH:~/SAM/zig-linux-x86_64-0.12.0
sudo zig build installsystemd 
sudo systemctl enable ly.service

cd ~/SAM
