#!/bin/bash

# Instalar dependencias
sudo apt install -y libpam0g-dev libxcb-xkb-dev

# Descargar zig 0.12.0
wget https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
tar -xvf zig-linux-x86_64-0.12.0.tar.xz > /dev/null

# Descargar ly
git clone https://github.com/fairyglade/ly && cd ly

# Compilar y activar servicio de systemd
export PATH=$PATH:~/SAM/zig-linux-x86_64-0.12.0
sudo zig build installsystemd 
sudo systemctl enable ly.service

cd ~/SAM
