#!/bin/bash

# Instalar dependencias
sudo apt install -y golang libgtk-3-dev libcairo2-dev libglib2.0-bin make

# Descargar nwg-look 0.2.6
wget https://github.com/nwg-piotr/nwg-look/archive/refs/tags/v0.2.6.zip
unzip v0.2.6.zip
cd nwg-look-0.2.6

# Compilar
make build
sudo make install

cd ..
