#!/bin/bash

# Instalar dependencias
sudo apt install -y golang libgtk-3-dev libcairo2-dev libglib2.0-bin

# Descargar nwg-look 0.2.6
wget https://github.com/nwg-piotr/nwg-look/archive/refs/tags/v0.2.6.zip > /dev/null
unzip v0.2.6.zip > /dev/null
cd nwg-look-0.2.6

# Compilar
printf "\nCompilando nwg-look...\nPuede tardar un tiempo, espere por favor.\n"
make build > /dev/null
sudo make install > /dev/null
printf "\nCompletado\n"

cd ~/SAM
